[versions]
geary = "0.33.0"
velocity = "3.4.0-SNAPSHOT"
discordsrv = "1.30.0"
placeholderapi = "2.11.6"

[libraries]
geary-papermc = { module = "com.mineinabyss:geary-papermc", version.ref = "geary" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
discordsrv = { module = "com.discordsrv:discordsrv", version.ref = "discordsrv" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
